import { Analytics } from "@vercel/analytics/next";
import localFont from "next/font/local";
import NavBar from "@/components/NavBar";
import "./globals.css";

const helvetica = localFont({
  variable: "--font-helvetica",
  src: [
    {
      path: "./fonts/helvetica/Helvetica-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/helvetica/Helvetica-LightOblique.woff2",
      weight: "300",
      style: "italic",
    },
    {
      path: "./fonts/helvetica/Helvetica.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/helvetica/Helvetica-Oblique.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/helvetica/Helvetica-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/helvetica/Helvetica-BoldOblique.woff2",
      weight: "700",
      style: "italic",
    },
  ],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className="h-dvh">
      <body
        className={`${helvetica.className} ${helvetica.variable} antialiased h-dvh bg-primary text-secondary`}
      >
        <NavBar />
        {children}
        <Analytics />
      </body>
    </html>
  );
}
